language: generic

sudo: required
services:
  - docker
 
before_install:
  - docker build -t lab4957/docker-react -f Dockerfile.dev .
   
script:
  - docker run -e CI=true lab4957/docker-react npm run test